version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/golang/dep/cmd/dep
  pre_build: 
    commands:
      - pwd
      - find .
      - export GOPATH=/go
      - echo $GOPATH
      - mkdir -p /go/src/${GITHUB_REPO}
      - ln -s -v `pwd` /go/src/${GITHUB_REPO}
      - ls -l /go/src/${GITHUB_REPO}
      - echo ${GITHUB_REPO}
      - cd /go/src/${GITHUB_REPO}
      - pwd
      - dep ensure
      # Ensure code passes all lint tests
      # - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:

      # Build our application
      - go build -o app

artifacts:
  files:
    - app