version: 0.2

phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/golang/dep/cmd/dep
  pre_build: 
    commands:
      - pwd
      - find .
      - export GOPATH=/go
      - echo $GOPATHe 
      - echo `pwd`
      - mkdir -p /go/src/${GITHUB_REPO}
      - cp -a ${CODEBUILD_SRC_DIR}/. /go/src/${GITHUB_REPO}
      - ls -l /go/src/${GITHUB_REPO}
      - echo ${GITHUB_REPO}
      - cd  ${GOPATH}/src/${GITHUB_REPO}
      - pwd 
      - dep ensure
      # Ensure code passes all lint tests
      # - golint -set_exit_status

      # Run all tests included with our application

  build:
    commands:
      - 
      # Build our application
      - cd  ${GOPATH}/src/${GITHUB_REPO}
      - go build -o ${CODEBUILD_SRC_DIR}/app

artifacts:
  files:
    - app