version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/golang/dep/cmd/dep
  pre_build: 
    commands:
      - pwd
      - find .
      - echo $GOPATH
      - mkdir -p /go/src/$GITHUB_REPO
      - ln -s `pwd` /go/src/$GITHUB_REPO
      - ls -l /go
      - echo $GITHUB_REPO
      - cd /go/src/$GITHUB_REPO
      - dep ensure
      # Ensure code passes all lint tests
      # - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:

      # Build our application
      - go build -o app

artifacts:
  files:
    - app